package com.cozary.colored_water.init;

import com.cozary.colored_water.ColoredWater;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.LiquidBlock;
import net.minecraft.world.level.block.state.BlockBehaviour;

import java.util.function.Supplier;

import static com.cozary.colored_water.init.ModFluids.*;


public class ModBlocks {
    public static final RegistrationProvider<Block> BLOCKS = RegistrationProvider.get(Registries.BLOCK, ColoredWater.MOD_ID);

    public static Supplier<Block> WHITE_WATER_BLOCK = BLOCKS.register("white_water_block", () -> new LiquidBlock(STILL_WHITE_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "white_water_block")))));
    public static Supplier<Block> CONDENSE_WHITE_WATER_BLOCK = BLOCKS.register("condense_white_water_block", () -> new LiquidBlock(STILL_CONDENSE_WHITE_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_white_water_block")))));
    public static Supplier<Block> LUMINOUS_WHITE_WATER_BLOCK = BLOCKS.register("luminous_white_water_block", () -> new LiquidBlock(STILL_LUMINOUS_WHITE_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_white_water_block"))).lightLevel(state -> 15)));
    public static Supplier<Block> LUMINOUS_CONDENSE_WHITE_WATER_BLOCK = BLOCKS.register("luminous_condense_white_water_block", () -> new LiquidBlock(STILL_LUMINOUS_CONDENSE_WHITE_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_white_water_block"))).lightLevel(state -> 15)));

    public static Supplier<Block> ORANGE_WATER_BLOCK = BLOCKS.register("orange_water_block", () -> new LiquidBlock(STILL_ORANGE_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "orange_water_block")))));
    public static Supplier<Block> CONDENSE_ORANGE_WATER_BLOCK = BLOCKS.register("condense_orange_water_block", () -> new LiquidBlock(STILL_CONDENSE_ORANGE_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_orange_water_block")))));
    public static Supplier<Block> LUMINOUS_ORANGE_WATER_BLOCK = BLOCKS.register("luminous_orange_water_block", () -> new LiquidBlock(STILL_LUMINOUS_ORANGE_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_orange_water_block"))).lightLevel(state -> 15)));
    public static Supplier<Block> LUMINOUS_CONDENSE_ORANGE_WATER_BLOCK = BLOCKS.register("luminous_condense_orange_water_block", () -> new LiquidBlock(STILL_LUMINOUS_CONDENSE_ORANGE_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_orange_water_block"))).lightLevel(state -> 15)));

    public static Supplier<Block> MAGENTA_WATER_BLOCK = BLOCKS.register("magenta_water_block", () -> new LiquidBlock(STILL_MAGENTA_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "magenta_water_block")))));
    public static Supplier<Block> CONDENSE_MAGENTA_WATER_BLOCK = BLOCKS.register("condense_magenta_water_block", () -> new LiquidBlock(STILL_CONDENSE_MAGENTA_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_magenta_water_block")))));
    public static Supplier<Block> LUMINOUS_MAGENTA_WATER_BLOCK = BLOCKS.register("luminous_magenta_water_block", () -> new LiquidBlock(STILL_LUMINOUS_MAGENTA_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_magenta_water_block"))).lightLevel(state -> 15)));
    public static Supplier<Block> LUMINOUS_CONDENSE_MAGENTA_WATER_BLOCK = BLOCKS.register("luminous_condense_magenta_water_block", () -> new LiquidBlock(STILL_LUMINOUS_CONDENSE_MAGENTA_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_magenta_water_block"))).lightLevel(state -> 15)));

    public static Supplier<Block> LIGHT_BLUE_WATER_BLOCK = BLOCKS.register("light_blue_water_block", () -> new LiquidBlock(STILL_LIGHT_BLUE_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "light_blue_water_block")))));
    public static Supplier<Block> CONDENSE_LIGHT_BLUE_WATER_BLOCK = BLOCKS.register("condense_light_blue_water_block", () -> new LiquidBlock(STILL_CONDENSE_LIGHT_BLUE_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_light_blue_water_block")))));
    public static Supplier<Block> LUMINOUS_LIGHT_BLUE_WATER_BLOCK = BLOCKS.register("luminous_light_blue_water_block", () -> new LiquidBlock(STILL_LUMINOUS_LIGHT_BLUE_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_light_blue_water_block"))).lightLevel(state -> 15)));
    public static Supplier<Block> LUMINOUS_CONDENSE_LIGHT_BLUE_WATER_BLOCK = BLOCKS.register("luminous_condense_light_blue_water_block", () -> new LiquidBlock(STILL_LUMINOUS_CONDENSE_LIGHT_BLUE_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_light_blue_water_block"))).lightLevel(state -> 15)));

    public static Supplier<Block> YELLOW_WATER_BLOCK = BLOCKS.register("yellow_water_block", () -> new LiquidBlock(STILL_YELLOW_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "yellow_water_block")))));
    public static Supplier<Block> CONDENSE_YELLOW_WATER_BLOCK = BLOCKS.register("condense_yellow_water_block", () -> new LiquidBlock(STILL_CONDENSE_YELLOW_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_yellow_water_block")))));
    public static Supplier<Block> LUMINOUS_YELLOW_WATER_BLOCK = BLOCKS.register("luminous_yellow_water_block", () -> new LiquidBlock(STILL_LUMINOUS_YELLOW_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_yellow_water_block"))).lightLevel(state -> 15)));
    public static Supplier<Block> LUMINOUS_CONDENSE_YELLOW_WATER_BLOCK = BLOCKS.register("luminous_condense_yellow_water_block", () -> new LiquidBlock(STILL_LUMINOUS_CONDENSE_YELLOW_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_yellow_water_block"))).lightLevel(state -> 15)));

    public static Supplier<Block> LIME_WATER_BLOCK = BLOCKS.register("lime_water_block", () -> new LiquidBlock(STILL_LIME_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "lime_water_block")))));
    public static Supplier<Block> CONDENSE_LIME_WATER_BLOCK = BLOCKS.register("condense_lime_water_block", () -> new LiquidBlock(STILL_CONDENSE_LIME_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_lime_water_block")))));
    public static Supplier<Block> LUMINOUS_LIME_WATER_BLOCK = BLOCKS.register("luminous_lime_water_block", () -> new LiquidBlock(STILL_LUMINOUS_LIME_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_lime_water_block"))).lightLevel(state -> 15)));
    public static Supplier<Block> LUMINOUS_CONDENSE_LIME_WATER_BLOCK = BLOCKS.register("luminous_condense_lime_water_block", () -> new LiquidBlock(STILL_LUMINOUS_CONDENSE_LIME_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_lime_water_block"))).lightLevel(state -> 15)));

    public static Supplier<Block> PINK_WATER_BLOCK = BLOCKS.register("pink_water_block", () -> new LiquidBlock(STILL_PINK_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "pink_water_block")))));
    public static Supplier<Block> CONDENSE_PINK_WATER_BLOCK = BLOCKS.register("condense_pink_water_block", () -> new LiquidBlock(STILL_CONDENSE_PINK_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_pink_water_block")))));
    public static Supplier<Block> LUMINOUS_PINK_WATER_BLOCK = BLOCKS.register("luminous_pink_water_block", () -> new LiquidBlock(STILL_LUMINOUS_PINK_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_pink_water_block"))).lightLevel(state -> 15)));
    public static Supplier<Block> LUMINOUS_CONDENSE_PINK_WATER_BLOCK = BLOCKS.register("luminous_condense_pink_water_block", () -> new LiquidBlock(STILL_LUMINOUS_CONDENSE_PINK_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_pink_water_block"))).lightLevel(state -> 15)));

    public static Supplier<Block> GRAY_WATER_BLOCK = BLOCKS.register("gray_water_block", () -> new LiquidBlock(STILL_GRAY_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "gray_water_block")))));
    public static Supplier<Block> CONDENSE_GRAY_WATER_BLOCK = BLOCKS.register("condense_gray_water_block", () -> new LiquidBlock(STILL_CONDENSE_GRAY_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_gray_water_block")))));
    public static Supplier<Block> LUMINOUS_GRAY_WATER_BLOCK = BLOCKS.register("luminous_gray_water_block", () -> new LiquidBlock(STILL_LUMINOUS_GRAY_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_gray_water_block"))).lightLevel(state -> 15)));
    public static Supplier<Block> LUMINOUS_CONDENSE_GRAY_WATER_BLOCK = BLOCKS.register("luminous_condense_gray_water_block", () -> new LiquidBlock(STILL_LUMINOUS_CONDENSE_GRAY_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_gray_water_block"))).lightLevel(state -> 15)));

    public static Supplier<Block> LIGHT_GRAY_WATER_BLOCK = BLOCKS.register("light_gray_water_block", () -> new LiquidBlock(STILL_LIGHT_GRAY_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "light_gray_water_block")))));
    public static Supplier<Block> CONDENSE_LIGHT_GRAY_WATER_BLOCK = BLOCKS.register("condense_light_gray_water_block", () -> new LiquidBlock(STILL_CONDENSE_LIGHT_GRAY_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_light_gray_water_block")))));
    public static Supplier<Block> LUMINOUS_LIGHT_GRAY_WATER_BLOCK = BLOCKS.register("luminous_light_gray_water_block", () -> new LiquidBlock(STILL_LUMINOUS_LIGHT_GRAY_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_light_gray_water_block"))).lightLevel(state -> 15)));
    public static Supplier<Block> LUMINOUS_CONDENSE_LIGHT_GRAY_WATER_BLOCK = BLOCKS.register("luminous_condense_light_gray_water_block", () -> new LiquidBlock(STILL_LUMINOUS_CONDENSE_LIGHT_GRAY_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_light_gray_water_block"))).lightLevel(state -> 15)));

    public static Supplier<Block> CYAN_WATER_BLOCK = BLOCKS.register("cyan_water_block", () -> new LiquidBlock(STILL_CYAN_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "cyan_water_block")))));
    public static Supplier<Block> CONDENSE_CYAN_WATER_BLOCK = BLOCKS.register("condense_cyan_water_block", () -> new LiquidBlock(STILL_CONDENSE_CYAN_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_cyan_water_block")))));
    public static Supplier<Block> LUMINOUS_CYAN_WATER_BLOCK = BLOCKS.register("luminous_cyan_water_block", () -> new LiquidBlock(STILL_LUMINOUS_CYAN_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_cyan_water_block"))).lightLevel(state -> 15)));
    public static Supplier<Block> LUMINOUS_CONDENSE_CYAN_WATER_BLOCK = BLOCKS.register("luminous_condense_cyan_water_block", () -> new LiquidBlock(STILL_LUMINOUS_CONDENSE_CYAN_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_cyan_water_block"))).lightLevel(state -> 15)));

    public static Supplier<Block> BLUE_WATER_BLOCK = BLOCKS.register("blue_water_block", () -> new LiquidBlock(STILL_BLUE_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "blue_water_block")))));
    public static Supplier<Block> CONDENSE_BLUE_WATER_BLOCK = BLOCKS.register("condense_blue_water_block", () -> new LiquidBlock(STILL_CONDENSE_BLUE_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_blue_water_block")))));
    public static Supplier<Block> LUMINOUS_BLUE_WATER_BLOCK = BLOCKS.register("luminous_blue_water_block", () -> new LiquidBlock(STILL_LUMINOUS_BLUE_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_blue_water_block"))).lightLevel(state -> 15)));
    public static Supplier<Block> LUMINOUS_CONDENSE_BLUE_WATER_BLOCK = BLOCKS.register("luminous_condense_blue_water_block", () -> new LiquidBlock(STILL_LUMINOUS_CONDENSE_BLUE_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_blue_water_block"))).lightLevel(state -> 15)));

    public static Supplier<Block> PURPLE_WATER_BLOCK = BLOCKS.register("purple_water_block", () -> new LiquidBlock(STILL_PURPLE_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "purple_water_block")))));
    public static Supplier<Block> CONDENSE_PURPLE_WATER_BLOCK = BLOCKS.register("condense_purple_water_block", () -> new LiquidBlock(STILL_CONDENSE_PURPLE_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_purple_water_block")))));
    public static Supplier<Block> LUMINOUS_PURPLE_WATER_BLOCK = BLOCKS.register("luminous_purple_water_block", () -> new LiquidBlock(STILL_LUMINOUS_PURPLE_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_purple_water_block"))).lightLevel(state -> 15)));
    public static Supplier<Block> LUMINOUS_CONDENSE_PURPLE_WATER_BLOCK = BLOCKS.register("luminous_condense_purple_water_block", () -> new LiquidBlock(STILL_LUMINOUS_CONDENSE_PURPLE_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_purple_water_block"))).lightLevel(state -> 15)));

    public static Supplier<Block> BLACK_WATER_BLOCK = BLOCKS.register("black_water_block", () -> new LiquidBlock(STILL_BLACK_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "black_water_block")))));
    public static Supplier<Block> CONDENSE_BLACK_WATER_BLOCK = BLOCKS.register("condense_black_water_block", () -> new LiquidBlock(STILL_CONDENSE_BLACK_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_black_water_block")))));
    public static Supplier<Block> LUMINOUS_BLACK_WATER_BLOCK = BLOCKS.register("luminous_black_water_block", () -> new LiquidBlock(STILL_LUMINOUS_BLACK_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_black_water_block"))).lightLevel(state -> 15)));
    public static Supplier<Block> LUMINOUS_CONDENSE_BLACK_WATER_BLOCK = BLOCKS.register("luminous_condense_black_water_block", () -> new LiquidBlock(STILL_LUMINOUS_CONDENSE_BLACK_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_black_water_block"))).lightLevel(state -> 15)));

    public static Supplier<Block> GREEN_WATER_BLOCK = BLOCKS.register("green_water_block", () -> new LiquidBlock(STILL_GREEN_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "green_water_block")))));
    public static Supplier<Block> CONDENSE_GREEN_WATER_BLOCK = BLOCKS.register("condense_green_water_block", () -> new LiquidBlock(STILL_CONDENSE_GREEN_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_green_water_block")))));
    public static Supplier<Block> LUMINOUS_GREEN_WATER_BLOCK = BLOCKS.register("luminous_green_water_block", () -> new LiquidBlock(STILL_LUMINOUS_GREEN_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_green_water_block"))).lightLevel(state -> 15)));
    public static Supplier<Block> LUMINOUS_CONDENSE_GREEN_WATER_BLOCK = BLOCKS.register("luminous_condense_green_water_block", () -> new LiquidBlock(STILL_LUMINOUS_CONDENSE_GREEN_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_green_water_block"))).lightLevel(state -> 15)));

    public static Supplier<Block> RED_WATER_BLOCK = BLOCKS.register("red_water_block", () -> new LiquidBlock(STILL_RED_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "red_water_block")))));
    public static Supplier<Block> CONDENSE_RED_WATER_BLOCK = BLOCKS.register("condense_red_water_block", () -> new LiquidBlock(STILL_CONDENSE_RED_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_red_water_block")))));
    public static Supplier<Block> LUMINOUS_RED_WATER_BLOCK = BLOCKS.register("luminous_red_water_block", () -> new LiquidBlock(STILL_LUMINOUS_RED_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_red_water_block"))).lightLevel(state -> 15)));
    public static Supplier<Block> LUMINOUS_CONDENSE_RED_WATER_BLOCK = BLOCKS.register("luminous_condense_red_water_block", () -> new LiquidBlock(STILL_LUMINOUS_CONDENSE_RED_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_red_water_block"))).lightLevel(state -> 15)));

    public static Supplier<Block> BROWN_WATER_BLOCK = BLOCKS.register("brown_water_block", () -> new LiquidBlock(STILL_BROWN_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "brown_water_block")))));
    public static Supplier<Block> CONDENSE_BROWN_WATER_BLOCK = BLOCKS.register("condense_brown_water_block", () -> new LiquidBlock(STILL_CONDENSE_BROWN_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_brown_water_block")))));
    public static Supplier<Block> LUMINOUS_BROWN_WATER_BLOCK = BLOCKS.register("luminous_brown_water_block", () -> new LiquidBlock(STILL_LUMINOUS_BROWN_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_brown_water_block"))).lightLevel(state -> 15)));
    public static Supplier<Block> LUMINOUS_CONDENSE_BROWN_WATER_BLOCK = BLOCKS.register("luminous_condense_brown_water_block", () -> new LiquidBlock(STILL_LUMINOUS_CONDENSE_BROWN_WATER.get(), BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).setId(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_brown_water_block"))).lightLevel(state -> 15)));

    public static void loadClass() {
    }

}
