package com.cozary.colored_water.init;

import com.cozary.colored_water.ColoredWater;
import com.cozary.colored_water.cauldrons.behaviour.ColorCauldronBehavior;
import com.cozary.colored_water.cauldrons.behaviour.CondenseCauldronBehavior;
import com.cozary.colored_water.cauldrons.behaviour.LuminousCauldronBehavior;
import com.cozary.colored_water.cauldrons.behaviour.LuminousCondenseCauldronBehavior;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.LayeredCauldronBlock;
import net.minecraft.world.level.block.state.BlockBehaviour;

import java.util.function.Supplier;

import static net.minecraft.world.level.block.Blocks.CAULDRON;

public class ModCauldrons {

    public static final RegistrationProvider<Block> BLOCKS = RegistrationProvider.get(Registries.BLOCK, ColoredWater.MOD_ID);

    public static final Supplier<Block> MAGENTA_WATER_CAULDRON = BLOCKS.register("magenta_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.MAGENTA_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "magenta_water_cauldron")))));
    public static final Supplier<Block> PURPLE_WATER_CAULDRON = BLOCKS.register("purple_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.PURPLE_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "purple_water_cauldron")))));
    public static final Supplier<Block> GREEN_WATER_CAULDRON = BLOCKS.register("green_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.GREEN_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "green_water_cauldron")))));
    public static final Supplier<Block> YELLOW_WATER_CAULDRON = BLOCKS.register("yellow_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.YELLOW_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "yellow_water_cauldron")))));
    public static final Supplier<Block> LIME_WATER_CAULDRON = BLOCKS.register("lime_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.LIME_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "lime_water_cauldron")))));
    public static final Supplier<Block> PINK_WATER_CAULDRON = BLOCKS.register("pink_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.PINK_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "pink_water_cauldron")))));
    public static final Supplier<Block> RED_WATER_CAULDRON = BLOCKS.register("red_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.RED_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "red_water_cauldron")))));
    public static final Supplier<Block> BLACK_WATER_CAULDRON = BLOCKS.register("black_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.BLACK_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "black_water_cauldron")))));
    public static final Supplier<Block> BROWN_WATER_CAULDRON = BLOCKS.register("brown_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.BROWN_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "brown_water_cauldron")))));
    public static final Supplier<Block> BLUE_WATER_CAULDRON = BLOCKS.register("blue_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.BLUE_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "blue_water_cauldron")))));
    public static final Supplier<Block> CYAN_WATER_CAULDRON = BLOCKS.register("cyan_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.CYAN_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "cyan_water_cauldron")))));
    public static final Supplier<Block> LIGHT_GRAY_WATER_CAULDRON = BLOCKS.register("light_gray_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.LIGHT_GRAY_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "light_gray_water_cauldron")))));
    public static final Supplier<Block> GRAY_WATER_CAULDRON = BLOCKS.register("gray_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.GRAY_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "gray_water_cauldron")))));
    public static final Supplier<Block> LIGHT_BLUE_WATER_CAULDRON = BLOCKS.register("light_blue_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.LIGHT_BLUE_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "light_blue_water_cauldron")))));
    public static final Supplier<Block> ORANGE_WATER_CAULDRON = BLOCKS.register("orange_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.ORANGE_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "orange_water_cauldron")))));
    public static final Supplier<Block> WHITE_WATER_CAULDRON = BLOCKS.register("white_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.WHITE_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "white_water_cauldron")))));
    public static final Supplier<Block> CONDENSE_MAGENTA_WATER_CAULDRON = BLOCKS.register("condense_magenta_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_MAGENTA_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_magenta_water_cauldron")))));
    public static final Supplier<Block> CONDENSE_PURPLE_WATER_CAULDRON = BLOCKS.register("condense_purple_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_PURPLE_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_purple_water_cauldron")))));
    public static final Supplier<Block> CONDENSE_GREEN_WATER_CAULDRON = BLOCKS.register("condense_green_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_GREEN_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_green_water_cauldron")))));
    public static final Supplier<Block> CONDENSE_YELLOW_WATER_CAULDRON = BLOCKS.register("condense_yellow_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_YELLOW_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_yellow_water_cauldron")))));
    public static final Supplier<Block> CONDENSE_LIME_WATER_CAULDRON = BLOCKS.register("condense_lime_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_LIME_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_lime_water_cauldron")))));
    public static final Supplier<Block> CONDENSE_PINK_WATER_CAULDRON = BLOCKS.register("condense_pink_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_PINK_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_pink_water_cauldron")))));
    public static final Supplier<Block> CONDENSE_RED_WATER_CAULDRON = BLOCKS.register("condense_red_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_RED_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_red_water_cauldron")))));
    public static final Supplier<Block> CONDENSE_BLACK_WATER_CAULDRON = BLOCKS.register("condense_black_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_BLACK_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_black_water_cauldron")))));
    public static final Supplier<Block> CONDENSE_BROWN_WATER_CAULDRON = BLOCKS.register("condense_brown_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_BROWN_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_brown_water_cauldron")))));
    public static final Supplier<Block> CONDENSE_BLUE_WATER_CAULDRON = BLOCKS.register("condense_blue_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_BLUE_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_blue_water_cauldron")))));
    public static final Supplier<Block> CONDENSE_CYAN_WATER_CAULDRON = BLOCKS.register("condense_cyan_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_CYAN_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_cyan_water_cauldron")))));
    public static final Supplier<Block> CONDENSE_LIGHT_GRAY_WATER_CAULDRON = BLOCKS.register("condense_light_gray_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_LIGHT_GRAY_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_light_gray_water_cauldron")))));
    public static final Supplier<Block> CONDENSE_GRAY_WATER_CAULDRON = BLOCKS.register("condense_gray_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_GRAY_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_gray_water_cauldron")))));
    public static final Supplier<Block> CONDENSE_LIGHT_BLUE_WATER_CAULDRON = BLOCKS.register("condense_light_blue_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_LIGHT_BLUE_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_light_blue_water_cauldron")))));
    public static final Supplier<Block> CONDENSE_ORANGE_WATER_CAULDRON = BLOCKS.register("condense_orange_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_ORANGE_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_orange_water_cauldron")))));
    public static final Supplier<Block> CONDENSE_WHITE_WATER_CAULDRON = BLOCKS.register("condense_white_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_WHITE_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "condense_white_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_MAGENTA_WATER_CAULDRON = BLOCKS.register("luminous_magenta_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_MAGENTA_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_magenta_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_PURPLE_WATER_CAULDRON = BLOCKS.register("luminous_purple_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_PURPLE_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_purple_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_GREEN_WATER_CAULDRON = BLOCKS.register("luminous_green_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_GREEN_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_green_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_YELLOW_WATER_CAULDRON = BLOCKS.register("luminous_yellow_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_YELLOW_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_yellow_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_LIME_WATER_CAULDRON = BLOCKS.register("luminous_lime_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_LIME_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_lime_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_PINK_WATER_CAULDRON = BLOCKS.register("luminous_pink_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_PINK_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_pink_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_RED_WATER_CAULDRON = BLOCKS.register("luminous_red_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_RED_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_red_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_BLACK_WATER_CAULDRON = BLOCKS.register("luminous_black_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_BLACK_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_black_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_BROWN_WATER_CAULDRON = BLOCKS.register("luminous_brown_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_BROWN_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_brown_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_BLUE_WATER_CAULDRON = BLOCKS.register("luminous_blue_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_BLUE_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_blue_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_CYAN_WATER_CAULDRON = BLOCKS.register("luminous_cyan_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_CYAN_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_cyan_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_LIGHT_GRAY_WATER_CAULDRON = BLOCKS.register("luminous_light_gray_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_LIGHT_GRAY_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_light_gray_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_GRAY_WATER_CAULDRON = BLOCKS.register("luminous_gray_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_GRAY_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_gray_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_LIGHT_BLUE_WATER_CAULDRON = BLOCKS.register("luminous_light_blue_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_LIGHT_BLUE_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_light_blue_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_ORANGE_WATER_CAULDRON = BLOCKS.register("luminous_orange_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_ORANGE_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_orange_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_WHITE_WATER_CAULDRON = BLOCKS.register("luminous_white_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_WHITE_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_white_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_CONDENSE_MAGENTA_WATER_CAULDRON = BLOCKS.register("luminous_condense_magenta_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_MAGENTA_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_magenta_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_CONDENSE_PURPLE_WATER_CAULDRON = BLOCKS.register("luminous_condense_purple_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_PURPLE_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_purple_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_CONDENSE_GREEN_WATER_CAULDRON = BLOCKS.register("luminous_condense_green_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_GREEN_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_green_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_CONDENSE_YELLOW_WATER_CAULDRON = BLOCKS.register("luminous_condense_yellow_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_YELLOW_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_yellow_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_CONDENSE_LIME_WATER_CAULDRON = BLOCKS.register("luminous_condense_lime_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_LIME_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_lime_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_CONDENSE_PINK_WATER_CAULDRON = BLOCKS.register("luminous_condense_pink_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_PINK_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_pink_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_CONDENSE_RED_WATER_CAULDRON = BLOCKS.register("luminous_condense_red_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_RED_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_red_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_CONDENSE_BLACK_WATER_CAULDRON = BLOCKS.register("luminous_condense_black_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_BLACK_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_black_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_CONDENSE_BROWN_WATER_CAULDRON = BLOCKS.register("luminous_condense_brown_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_BROWN_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_brown_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_CONDENSE_BLUE_WATER_CAULDRON = BLOCKS.register("luminous_condense_blue_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_BLUE_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_blue_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_CONDENSE_CYAN_WATER_CAULDRON = BLOCKS.register("luminous_condense_cyan_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_CYAN_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_cyan_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_CONDENSE_LIGHT_GRAY_WATER_CAULDRON = BLOCKS.register("luminous_condense_light_gray_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_LIGHT_GRAY_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_light_gray_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_CONDENSE_GRAY_WATER_CAULDRON = BLOCKS.register("luminous_condense_gray_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_GRAY_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_gray_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_CONDENSE_LIGHT_BLUE_WATER_CAULDRON = BLOCKS.register("luminous_condense_light_blue_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_LIGHT_BLUE_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_light_blue_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_CONDENSE_ORANGE_WATER_CAULDRON = BLOCKS.register("luminous_condense_orange_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_ORANGE_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_orange_water_cauldron")))));
    public static final Supplier<Block> LUMINOUS_CONDENSE_WHITE_WATER_CAULDRON = BLOCKS.register("luminous_condense_white_water_cauldron", () -> new LayeredCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_WHITE_CAULDRON_BEHAVIOR, BlockBehaviour.Properties.ofFullCopy(CAULDRON).lightLevel(state -> 15).setId(ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(ColoredWater.MOD_ID, "luminous_condense_white_water_cauldron")))));

    public static void loadClass() {
    }

}
