modLoader = "javafml"
loaderVersion = "[47,)"
license = "All rights reserved"

[[mods]]

modId = "colored_water"
version = "1.20.1-1.3.8"
displayName = "Colored Water"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/colored_water"
issueTrackerURL = "https://github.com/Cozary/Issue-Tracker"
authors = "Cozary"
credits = "Thanks for download this mod uwu"
description = '''
    This mod adds colored water!
    '''

[[dependencies.colored_water]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.colored_water]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"