package com.cozary.colored_water.init;

import com.cozary.colored_water.cauldrons.behaviour.ColorCauldronBehavior;
import com.cozary.colored_water.cauldrons.behaviour.CondenseCauldronBehavior;
import com.cozary.colored_water.cauldrons.behaviour.LuminousCauldronBehavior;
import com.cozary.colored_water.cauldrons.behaviour.LuminousCondenseCauldronBehavior;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.block.LeveledCauldronBlock;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;
import net.minecraft.world.biome.Biome;

import static com.cozary.colored_water.ColoredWater.MOD_ID;
import static net.minecraft.block.Blocks.CAULDRON;

public class ModCauldrons {

    public static final Block MAGENTA_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "magenta_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.MAGENTA_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block PURPLE_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "purple_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.PURPLE_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block GREEN_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "green_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.GREEN_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block YELLOW_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "yellow_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.YELLOW_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block LIME_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "lime_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.LIME_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block PINK_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "pink_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.PINK_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block RED_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "red_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.RED_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block BLACK_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "black_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.BLACK_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block BROWN_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "brown_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.BROWN_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block BLUE_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "blue_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.BLUE_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block CYAN_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "cyan_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.CYAN_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block LIGHT_GRAY_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "light_gray_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.LIGHT_GRAY_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block GRAY_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "gray_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.GRAY_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block LIGHT_BLUE_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "light_blue_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.LIGHT_BLUE_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block ORANGE_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "orange_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.ORANGE_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block WHITE_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "white_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, ColorCauldronBehavior.WHITE_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block CONDENSE_MAGENTA_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "condense_magenta_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_MAGENTA_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block CONDENSE_PURPLE_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "condense_purple_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_PURPLE_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block CONDENSE_GREEN_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "condense_green_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_GREEN_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block CONDENSE_YELLOW_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "condense_yellow_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_YELLOW_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block CONDENSE_LIME_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "condense_lime_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_LIME_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block CONDENSE_PINK_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "condense_pink_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_PINK_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block CONDENSE_RED_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "condense_red_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_RED_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block CONDENSE_BLACK_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "condense_black_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_BLACK_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block CONDENSE_BROWN_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "condense_brown_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_BROWN_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block CONDENSE_BLUE_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "condense_blue_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_BLUE_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block CONDENSE_CYAN_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "condense_cyan_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_CYAN_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block CONDENSE_LIGHT_GRAY_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "condense_light_gray_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_LIGHT_GRAY_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block CONDENSE_GRAY_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "condense_gray_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_GRAY_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block CONDENSE_LIGHT_BLUE_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "condense_light_blue_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_LIGHT_BLUE_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block CONDENSE_ORANGE_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "condense_orange_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_ORANGE_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block CONDENSE_WHITE_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "condense_white_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, CondenseCauldronBehavior.CONDENSE_WHITE_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON)));
    public static final Block LUMINOUS_MAGENTA_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_magenta_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_MAGENTA_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_PURPLE_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_purple_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_PURPLE_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_GREEN_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_green_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_GREEN_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_YELLOW_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_yellow_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_YELLOW_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_LIME_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_lime_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_LIME_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_PINK_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_pink_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_PINK_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_RED_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_red_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_RED_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_BLACK_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_black_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_BLACK_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_BROWN_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_brown_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_BROWN_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_BLUE_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_blue_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_BLUE_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_CYAN_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_cyan_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_CYAN_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_LIGHT_GRAY_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_light_gray_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_LIGHT_GRAY_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_GRAY_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_gray_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_GRAY_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_LIGHT_BLUE_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_light_blue_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_LIGHT_BLUE_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_ORANGE_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_orange_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_ORANGE_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_WHITE_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_white_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCauldronBehavior.LUMINOUS_WHITE_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_CONDENSE_MAGENTA_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_condense_magenta_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_MAGENTA_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_CONDENSE_PURPLE_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_condense_purple_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_PURPLE_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_CONDENSE_GREEN_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_condense_green_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_GREEN_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_CONDENSE_YELLOW_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_condense_yellow_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_YELLOW_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_CONDENSE_LIME_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_condense_lime_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_LIME_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_CONDENSE_PINK_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_condense_pink_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_PINK_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_CONDENSE_RED_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_condense_red_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_RED_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_CONDENSE_BLACK_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_condense_black_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_BLACK_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_CONDENSE_BROWN_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_condense_brown_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_BROWN_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_CONDENSE_BLUE_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_condense_blue_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_BLUE_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_CONDENSE_CYAN_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_condense_cyan_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_CYAN_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_CONDENSE_LIGHT_GRAY_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_condense_light_gray_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_LIGHT_GRAY_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_CONDENSE_GRAY_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_condense_gray_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_GRAY_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_CONDENSE_LIGHT_BLUE_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_condense_light_blue_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_LIGHT_BLUE_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_CONDENSE_ORANGE_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_condense_orange_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_ORANGE_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));
    public static final Block LUMINOUS_CONDENSE_WHITE_WATER_CAULDRON = Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "luminous_condense_white_water_cauldron"), new LeveledCauldronBlock(Biome.Precipitation.RAIN, LuminousCondenseCauldronBehavior.LUMINOUS_CONDENSE_WHITE_CAULDRON_BEHAVIOR, AbstractBlock.Settings.copy(CAULDRON).luminance(state -> 15)));

    public static void loadClass() {

    }

}